name: Retry Workflow Action
description: Github action to retry failed jobs within a github workflow.
author: 'hourki-actions'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: true
  workflow_run_id:
    description: 'Workflow Run ID'
    required: true
  max_retries:
    description: 'The maximum number of retries for failed jobs within a workflow'
    default: 3
outputs:
  rerun:
    description: approval if re-running should continu to next steps
  failed_jobs:
    description: number of failed jobs
  run_id:
    description: failed workflow run id
  repo:
    description: repository inputs

runs:
  using: 'docker'
  image: 'Dockerfile'
